# Generated by Django 3.0.7 on 2020-07-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('idCompra', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=100)),
                ('tienda', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Forma_Pago',
            fields=[
                ('idForma_pago', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre_propietario', models.CharField(max_length=50)),
                ('numero_tarjeta', models.IntegerField()),
                ('vencimiento_dia', models.DateField()),
                ('vencimiento_mes', models.DateField()),
                ('vencimiento_anio', models.DateField()),
            ],
        ),
    ]
