# Generated by Django 3.0.7 on 2020-07-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('idCuenta', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=10)),
                ('passwordNuevo', models.CharField(max_length=15)),
                ('passwordConfirmado', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('ciudad', models.TextField(max_length=30)),
                ('codigoPostal', models.CharField(max_length=5)),
                ('direccion', models.TextField(max_length=50)),
            ],
        ),
    ]
