# Generated by Django 3.0.7 on 2020-07-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20200727_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumidor',
            name='pw',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
