# Generated by Django 3.0.7 on 2020-08-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_auto_20200801_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='idCatProd',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='idProd',
        ),
        migrations.AlterField(
            model_name='carrito',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='subtotal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
