# Generated by Django 3.0.7 on 2020-08-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_auto_20200801_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forma_pago',
            name='fvencimiento',
        ),
        migrations.AddField(
            model_name='forma_pago',
            name='anio_vencimiento',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='forma_pago',
            name='mes_vencimiento',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='forma_pago',
            name='tipo_pago',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
