# Generated by Django 3.0.7 on 2020-08-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_auto_20200810_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocomprado',
            name='cantidad',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
