# Generated by Django 3.0.7 on 2020-11-15 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_carritoproducto_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='idForma_pago',
        ),
    ]
