# Generated by Django 3.0.7 on 2020-11-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_compras_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='status',
        ),
        migrations.AddField(
            model_name='productocomprado',
            name='status',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
