# Generated by Django 3.0.7 on 2020-11-15 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_auto_20201114_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productocomprado',
            name='cantidad',
        ),
    ]
