# Generated by Django 3.0.7 on 2020-07-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='logoTi',
            field=models.ImageField(upload_to='tienda'),
        ),
    ]
