# Generated by Django 3.0.7 on 2020-07-10 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_dash', '0002_auto_20200709_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='idUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagenProd',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='telefonoAdmin',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idProd',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='idAdmin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dash.Administrador'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='idTi',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='logoTi',
            field=models.ImageField(null=True, upload_to='tienda'),
        ),
    ]
