# Generated by Django 3.0.7 on 2020-07-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0003_auto_20200710_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='correoAdmin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
