# Generated by Django 3.0.7 on 2020-07-10 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('idVend', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombreVend', models.CharField(max_length=200)),
                ('edadVen', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('idUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='solicitudesvendedor',
            name='idVen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendedor.Vendedor'),
        ),
    ]
