# Generated by Django 3.0.7 on 2020-07-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0002_auto_20200710_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='edadVen',
        ),
        migrations.AddField(
            model_name='solicitudesvendedor',
            name='edadVen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudesvendedor',
            name='genero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
