# Generated by Django 3.0.7 on 2020-07-10 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0003_auto_20200710_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('idCatal', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=0, null=True)),
                ('idVen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendedor.Vendedor')),
            ],
        ),
    ]
