# Generated by Django 3.0.7 on 2020-07-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0004_catalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='correo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
