# Generated by Django 3.0.7 on 2020-07-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0005_vendedor_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='idCatal',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitudesvendedor',
            name='idSolVen',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='idVend',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
