# Generated by Django 3.0.7 on 2020-07-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0006_auto_20200710_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
