# Generated by Django 3.0.7 on 2020-07-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0008_auto_20200710_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudesvendedor',
            name='correV',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='solicitudesvendedor',
            name='direccionV',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='solicitudesvendedor',
            name='nombreV',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudesvendedor',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
