# Generated by Django 3.0.7 on 2020-07-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0009_auto_20200710_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudesvendedor',
            old_name='correV',
            new_name='correoV',
        ),
    ]
