# Generated by Django 3.0.7 on 2020-07-10 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0004_administrador_correoadmin'),
        ('vendedor', '0010_auto_20200710_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='idTien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dash.Tienda'),
        ),
    ]
