# Generated by Django 3.0.7 on 2020-08-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0012_catalogoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudesvendedor',
            name='noadmin',
            field=models.IntegerField(null=True),
        ),
    ]
