# Generated by Django 3.0.7 on 2020-08-04 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0013_solicitudesvendedor_noadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechazoSolicitud',
            fields=[
                ('idRechazo', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('idSolicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendedor.SolicitudesVendedor')),
            ],
        ),
    ]
