# Generated by Django 3.0.7 on 2020-08-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0014_rechazosolicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
