# Generated by Django 3.0.7 on 2020-08-10 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dash', '0004_administrador_correoadmin'),
        ('vendedor', '0015_vendedor_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas_vendedor',
            fields=[
                ('idVenta', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('venta', models.FloatField(blank=True, null=True)),
                ('idCatalogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendedor.Catalogo')),
                ('idProducto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dash.Producto')),
            ],
        ),
    ]
